### PR TITLE
Add standard deviation and median gradient metrics

### PR DESCRIPTION
**Pull request by PinkShnack**
As described in #19, these are some new metrics we have been trying out.

## To do:
- [x] Add std and med metrics
- [x] Test new metrics (and check if old ones need more tests)
- [x] Add an example showing a comparison for the example cell image.
- [x] update Changelog
- [x] ci/cd passes

### CODE REVIEW

**Comment by PinkShnack** [comment]
Hey @paulmueller, when building the docs locally, there seems to be some path issues for me. For example I get this:

```
fakefile.rst:11: WARNING: image file not readable: ../examplesrefocus_cell.jpg
fakefile.rst:9: WARNING: image file not readable: ../examplescompare_metrics.png
C:\Users\eoconne\Documents\Python\repos\nrefocus\docs\sec_examples.rst:9: WARNING: download file not readable: C:\Users\eoconne\Documents\Python\repos\nrefocus\examplesrefocus_cell.py 
C:\Users\eoconne\Documents\Python\repos\nrefocus\docs\sec_examples.rst:7: WARNING: download file not readable: C:\Users\eoconne\Documents\Python\repos\nrefocus\examplescompare_metrics.py
```

Note that I also had this when building docs in the previous MR, but it seems to build just fine on the main upstream branch (https://nrefocus.readthedocs.io/en/stable/sec_examples.html), even if it can't find the images for me. So I am hesitant to start changing things.

**Comment by paulmueller** [comment]
> Hey @paulmueller, when building the docs locally, there seems to be some path issues for me. For example I get this:
> 
> ```
> fakefile.rst:11: WARNING: image file not readable: ../examplesrefocus_cell.jpg
> fakefile.rst:9: WARNING: image file not readable: ../examplescompare_metrics.png
> C:\Users\eoconne\Documents\Python\repos\nrefocus\docs\sec_examples.rst:9: WARNING: download file not readable: C:\Users\eoconne\Documents\Python\repos\nrefocus\examplesrefocus_cell.py 
> C:\Users\eoconne\Documents\Python\repos\nrefocus\docs\sec_examples.rst:7: WARNING: download file not readable: C:\Users\eoconne\Documents\Python\repos\nrefocus\examplescompare_metrics.py
> ```
> 
> Note that I also had this when building docs in the previous MR, but it seems to build just fine on the main upstream branch (https://nrefocus.readthedocs.io/en/stable/sec_examples.html), even if it can't find the images for me. So I am hesitant to start changing things.

That looks like a path issue to me. The `examples/*` files are not found, probably because you are on Windows.

**Comment by PinkShnack** [comment]
I see this as an enhcancement `enh`, thoughts?

**Comment by PinkShnack** [comment]
Interestingly, the tests pass on py39 but some fail on py38. Probably due to some dependency update.
Here is the difference.

For the average gradient cropping test:
`function allclose at 0x00000246BDD9E430>(-8.79564628767923e-07, -8.795139152651752e-07, atol=0)`

For the std gradient cropping test:
`function allclose at 0x00000246BDD9E430>(-8.796638855298288e-07, -8.796339535413204e-07, atol=0)`

So there is a difference in value at 1e-11. Thoughts?

**Comment by paulmueller** [comment]
I managed to get everything working again. Please update the changelog and I will merge :rocket:

**Comment by PinkShnack** [comment]
Should be ready now @paulmueller :) Thanks for the changes. I also had a fix already committed but hadn't pushed it!

**Pull request merged**
